type Values = Record<string, string>;

const num = (values: Values, key: string) => {
  const value = Number(values[key]);
  if (!Number.isFinite(value)) throw new Error('invalid');
  return value;
};
const format = (value: number, locale: string, digits = 6) => new Intl.NumberFormat(locale, { maximumFractionDigits: digits }).format(value);
const words = (value: string) => value.toLocaleLowerCase().match(/[\p{L}\p{N}]+(?:['’][\p{L}\p{N}]+)*/gu) ?? [];
const uniqueLines = (items: string[]) => [...new Set(items)];
const gcd = (a: number, b: number): number => b ? gcd(b, a % b) : Math.abs(a);
const requireDate = (value: string) => { const date = new Date(`${value}${value.length === 10 ? 'T00:00:00' : ''}`); if (Number.isNaN(date.getTime())) throw new Error('invalid'); return date; };
const csvCell = (value: unknown) => { const cell = value == null ? '' : typeof value === 'object' ? JSON.stringify(value) : String(value); return /[",\n]/.test(cell) ? `"${cell.replaceAll('"', '""')}"` : cell; };
const shell = (value: string) => /^[\w./:@~-]+$/.test(value) ? value : `'${value.replaceAll("'", "'\\''")}'`;
const localText = (locale: string, en: string, es: string) => locale.startsWith('es') ? es : en;
const dateOnly = (date: Date) => date.toISOString().slice(0, 10);
const parseNumbers = (value: string) => value.split(/[\s,;]+/).filter(Boolean).map(Number).filter(Number.isFinite);

const morse: Record<string, string> = {
  A:'.-',B:'-...',C:'-.-.',D:'-..',E:'.',F:'..-.',G:'--.',H:'....',I:'..',J:'.---',K:'-.-',L:'.-..',M:'--',N:'-.',O:'---',P:'.--.',Q:'--.-',R:'.-.',S:'...',T:'-',U:'..-',V:'...-',W:'.--',X:'-..-',Y:'-.--',Z:'--..',
  0:'-----',1:'.----',2:'..---',3:'...--',4:'....-',5:'.....',6:'-....',7:'--...',8:'---..',9:'----.', '.':'.-.-.-', ',':'--..--', '?':'..--..', '!':'-.-.--', '-':'-....-', '/':'-..-.'
};
// Keep the common at-sign separate so the lookup table stays readable.
morse['@'] = '.--.-.';
const reverseMorse = Object.fromEntries(Object.entries(morse).map(([key, value]) => [value, key]));
const nato: Record<string, string> = { A:'Alfa',B:'Bravo',C:'Charlie',D:'Delta',E:'Echo',F:'Foxtrot',G:'Golf',H:'Hotel',I:'India',J:'Juliett',K:'Kilo',L:'Lima',M:'Mike',N:'November',O:'Oscar',P:'Papa',Q:'Quebec',R:'Romeo',S:'Sierra',T:'Tango',U:'Uniform',V:'Victor',W:'Whiskey',X:'X-ray',Y:'Yankee',Z:'Zulu',0:'Zero',1:'One',2:'Two',3:'Three',4:'Four',5:'Five',6:'Six',7:'Seven',8:'Eight',9:'Niner' };

const httpStatuses: Record<number, string> = { 100:'Continue',101:'Switching Protocols',200:'OK',201:'Created',202:'Accepted',204:'No Content',206:'Partial Content',301:'Moved Permanently',302:'Found',304:'Not Modified',307:'Temporary Redirect',308:'Permanent Redirect',400:'Bad Request',401:'Unauthorized',403:'Forbidden',404:'Not Found',405:'Method Not Allowed',408:'Request Timeout',409:'Conflict',410:'Gone',415:'Unsupported Media Type',418:"I'm a teapot",422:'Unprocessable Content',429:'Too Many Requests',500:'Internal Server Error',501:'Not Implemented',502:'Bad Gateway',503:'Service Unavailable',504:'Gateway Timeout' };
const mimeTypes: Record<string, string> = { html:'text/html',css:'text/css',js:'text/javascript',json:'application/json',xml:'application/xml',txt:'text/plain',csv:'text/csv',md:'text/markdown',pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',svg:'image/svg+xml',webp:'image/webp',avif:'image/avif',ico:'image/x-icon',mp3:'audio/mpeg',mp4:'video/mp4',webm:'video/webm',woff:'font/woff',woff2:'font/woff2',zip:'application/zip',wasm:'application/wasm' };
const ports: Record<number, string> = { 20:'FTP data',21:'FTP control',22:'SSH',23:'Telnet',25:'SMTP',53:'DNS',67:'DHCP server',68:'DHCP client',80:'HTTP',110:'POP3',123:'NTP',143:'IMAP',161:'SNMP',389:'LDAP',443:'HTTPS',465:'SMTPS',587:'SMTP submission',636:'LDAPS',993:'IMAPS',995:'POP3S',1433:'Microsoft SQL Server',1521:'Oracle Database',3000:'Common development server',3306:'MySQL',3389:'Remote Desktop',5432:'PostgreSQL',5672:'AMQP',6379:'Redis',8080:'Common HTTP alternative',8443:'Common HTTPS alternative',9200:'Elasticsearch',27017:'MongoDB' };

const sortObject = (value: unknown): unknown => Array.isArray(value) ? value.map(sortObject) : value && typeof value === 'object' ? Object.fromEntries(Object.keys(value as object).sort().map((key) => [key, sortObject((value as Record<string, unknown>)[key])])) : value;
const flatten = (value: unknown, prefix = '', result: Record<string, unknown> = {}) => {
  if (value && typeof value === 'object' && !Array.isArray(value)) Object.entries(value).forEach(([key, child]) => flatten(child, prefix ? `${prefix}.${key}` : key, result));
  else if (Array.isArray(value)) value.forEach((child, index) => flatten(child, `${prefix}.${index}`, result));
  else result[prefix] = value;
  return result;
};
const schemaFor = (value: unknown): Record<string, unknown> => {
  if (value === null) return { type: 'null' };
  if (Array.isArray(value)) return { type: 'array', items: value.length ? schemaFor(value[0]) : {} };
  if (typeof value === 'object') { const entries = Object.entries(value as object); return { type: 'object', properties: Object.fromEntries(entries.map(([key, child]) => [key, schemaFor(child)])), required: entries.map(([key]) => key) }; }
  return { type: typeof value === 'number' && Number.isInteger(value) ? 'integer' : typeof value };
};
const parseSemver = (value: string) => { const match = value.trim().replace(/^v/, '').match(/^(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.-]+))?$/); if (!match) throw new Error('invalid'); return { numbers: match.slice(1,4).map(Number), pre: match[4] ?? '' }; };
const hexRgb = (value: string) => { let hex=value.trim().replace('#',''); if (/^[0-9a-f]{3}$/i.test(hex)) hex=[...hex].map((x)=>x+x).join(''); if(!/^[0-9a-f]{6}$/i.test(hex))throw new Error('invalid'); return [0,2,4].map((i)=>parseInt(hex.slice(i,i+2),16)); };
const luminance = (rgb: number[]) => { const [r,g,b]=rgb.map((v)=>{const c=v/255;return c<=.04045?c/12.92:((c+.055)/1.055)**2.4});return .2126*r+.7152*g+.0722*b; };
const randomInt = (max: number) => { const data = new Uint32Array(1); crypto.getRandomValues(data); return data[0] % max; };
const randomFrom = <T>(values: T[]) => values[randomInt(values.length)];

export function executeExtraUtility(operation: string, values: Values, locale = 'en'): string {
  const input = values.input ?? '';
  const tr = (en: string, es: string) => localText(locale, en, es);
  const f = (value: number, digits = 6) => format(value, locale, digits);
  switch (operation) {
    case 'reverse-text': return Array.from(input).reverse().join('');
    case 'remove-line-breaks': return input.replace(/\s*\r?\n\s*/g, ' ').replace(/ {2,}/g, ' ').trim();
    case 'whitespace-normalizer': return input.replace(/[\t ]+/g,' ').replace(/ *\n */g,'\n').replace(/\n{3,}/g,'\n\n').trim();
    case 'word-frequency': { const counts = new Map<string,number>(); words(input).forEach((word)=>counts.set(word,(counts.get(word)??0)+1)); return [...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).map(([word,count])=>`${word}\t${count}`).join('\n'); }
    case 'reading-time-calculator': { const count=words(input).length,speed=num(values,'speed'); if(speed<=0)throw new Error('invalid'); const minutes=count/speed; return `${count} ${tr('words','palabras')}\n${tr('Estimated reading time','Tiempo estimado de lectura')}: ${minutes<1?`< 1 ${tr('minute','minuto')}`:`${f(minutes,1)} ${tr('minutes','minutos')}`}`; }
    case 'text-to-binary': return [...new TextEncoder().encode(input)].map((byte)=>byte.toString(2).padStart(8,'0')).join(' ');
    case 'binary-to-text': { const chunks=input.trim().split(/\s+/); if(chunks.some((chunk)=>!/^\d{8}$/.test(chunk)||/[2-9]/.test(chunk)))throw new Error('invalid'); return new TextDecoder().decode(Uint8Array.from(chunks.map((chunk)=>parseInt(chunk,2)))); }
    case 'text-to-morse': return input.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().split(/\s+/).map((part)=>[...part].map((char)=>morse[char]??char).join(' ')).join(' / ');
    case 'morse-to-text': return input.trim().split(/\s*\/\s*/).map((part)=>part.split(/\s+/).map((code)=>reverseMorse[code]??'?').join('')).join(' ');
    case 'nato-phonetic-converter': return [...input.toUpperCase()].map((char)=>nato[char]??(char===' '?' / ':char)).join(' ');
    case 'duplicate-line-finder': { const counts=new Map<string,number>(); input.split(/\r?\n/).map((line)=>line.trim()).filter(Boolean).forEach((line)=>counts.set(line,(counts.get(line)??0)+1)); const duplicates=[...counts].filter(([,count])=>count>1); return duplicates.length?duplicates.map(([line,count])=>`${count}×  ${line}`).join('\n'):tr('No duplicate lines found.','No se encontraron líneas duplicadas.'); }
    case 'line-number-adder': { const start=Math.trunc(num(values,'start')); return input.split(/\r?\n/).map((line,index)=>`${start+index}. ${line}`).join('\n'); }
    case 'line-number-remover': return input.split(/\r?\n/).map((line)=>line.replace(/^\s*(?:\d+[.):\-]|\[\d+\])\s*/,'')).join('\n');
    case 'prefix-suffix-adder': return input.split(/\r?\n/).map((line)=>`${values.prefix??''}${line}${values.suffix??''}`).join('\n');
    case 'text-repeater': { const count=Math.min(1000,Math.max(1,Math.trunc(num(values,'count')))); const separator=(values.separator??'\n').replaceAll('\\n','\n').replaceAll('\\t','\t'); return Array(count).fill(input).join(separator); }
    case 'word-shuffler': { const items=input.match(/\S+/g)??[]; for(let i=items.length-1;i>0;i--){const j=randomInt(i+1);[items[i],items[j]]=[items[j],items[i]];} return items.join(' '); }
    case 'sentence-sorter': return (input.match(/[^.!?]+[.!?]+|[^.!?]+$/g)??[]).map((x)=>x.trim()).filter(Boolean).sort((a,b)=>a.localeCompare(b,locale,{sensitivity:'base'})).join('\n');
    case 'extract-emails': return uniqueLines(input.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g)??[]).join('\n');
    case 'extract-urls': return uniqueLines(input.match(/https?:\/\/[^\s<>'"\])}]+/g)??[]).join('\n');
    case 'extract-numbers': return (input.match(/[-+]?\d+(?:[.,]\d+)?/g)??[]).join('\n');
    case 'remove-accents': return input.normalize('NFD').replace(/[\u0300-\u036f]/g,'');
    case 'invisible-character-detector': { const names:Record<string,string>={' ':'SPACE','\t':'TAB','\n':'LF','\r':'CR','\u00a0':'NBSP','\u200b':'ZERO WIDTH SPACE','\u200c':'ZERO WIDTH NON-JOINER','\u200d':'ZERO WIDTH JOINER','\ufeff':'BOM'}; const found=[...input].map((char,index)=>names[char]?`${index}: ${names[char]} (U+${char.codePointAt(0)!.toString(16).toUpperCase().padStart(4,'0')})`:null).filter(Boolean); return found.length?found.join('\n'):tr('No common invisible characters found.','No se encontraron caracteres invisibles habituales.'); }
    case 'text-statistics': { const chars=Array.from(input).length, noSpaces=Array.from(input.replace(/\s/g,'')).length, wordCount=words(input).length, lines=input?input.split(/\r?\n/).length:0, sentences=(input.match(/[.!?]+(?=\s|$)/g)??[]).length; return `${tr('Characters','Caracteres')}: ${chars}\n${tr('Without spaces','Sin espacios')}: ${noSpaces}\n${tr('Words','Palabras')}: ${wordCount}\n${tr('Lines','Líneas')}: ${lines}\n${tr('Sentences','Frases')}: ${sentences}`; }
    case 'alphabetical-word-sorter': return words(input).sort((a,b)=>a.localeCompare(b,locale,{sensitivity:'base'})).join('\n');
    case 'palindrome-checker': { const clean=input.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase().replace(/[^\p{L}\p{N}]/gu,''); const yes=clean.length>0&&clean===Array.from(clean).reverse().join(''); return yes?tr('Yes — it is a palindrome.','Sí: es un palíndromo.'):tr('No — it is not a palindrome.','No: no es un palíndromo.'); }

    case 'json-to-csv': { const data=JSON.parse(input); const rows=Array.isArray(data)?data:[data]; if(!rows.length||rows.some((row)=>!row||typeof row!=='object'||Array.isArray(row)))throw new Error('invalid'); const headers=uniqueLines(rows.flatMap((row)=>Object.keys(row))); return [headers.map(csvCell).join(','),...rows.map((row)=>headers.map((key)=>csvCell(row[key])).join(','))].join('\n'); }
    case 'json-path-extractor': { let result=JSON.parse(input); const path=values.path?.trim().replace(/\[(?:"([^"]+)"|'([^']+)'|(\d+))\]/g,'.$1$2$3').replace(/^\$\.?/,''); for(const key of path.split('.').filter(Boolean)){if(result==null||!(key in Object(result)))throw new Error('invalid');result=result[key];} return typeof result==='string'?result:JSON.stringify(result,null,2); }
    case 'query-string-parser': { const source=input.includes('?')?new URL(input).search:input.replace(/^\?/,''); const result:Record<string,string|string[]>={}; new URLSearchParams(source).forEach((value,key)=>{const current=result[key];result[key]=current===undefined?value:Array.isArray(current)?[...current,value]:[current,value]}); return JSON.stringify(result,null,2); }
    case 'query-string-builder': { const params=new URLSearchParams(); input.split(/\r?\n/).filter(Boolean).forEach((line)=>{const index=line.indexOf('=');if(index<0)throw new Error('invalid');params.append(line.slice(0,index).trim(),line.slice(index+1).trim())});return `?${params}`; }
    case 'unicode-escape-converter': return values.direction==='decode'?input.replace(/\\u\{([0-9a-f]+)\}|\\u([0-9a-f]{4})/gi,(_,wide,fixed)=>String.fromCodePoint(parseInt(wide||fixed,16))):[...input].map((char)=>{const code=char.codePointAt(0)!;return code<128?char:code<=0xffff?`\\u${code.toString(16).padStart(4,'0')}`:`\\u{${code.toString(16)}}`}).join('');
    case 'ascii-table': { const raw=input.trim(); const code=/^\d+$/.test(raw)?Number(raw):raw.charCodeAt(0); if(!Number.isInteger(code)||code<0||code>127)throw new Error('invalid'); const display=code<32||code===127?tr('control character','carácter de control'):String.fromCharCode(code); return `${tr('Character','Carácter')}: ${display}\nDecimal: ${code}\nHex: ${code.toString(16).toUpperCase().padStart(2,'0')}\nBinary: ${code.toString(2).padStart(8,'0')}`; }
    case 'hex-to-text': { const clean=input.replace(/0x/gi,'').replace(/[^0-9a-f]/gi,'');if(!clean||clean.length%2||!/^[0-9a-f]+$/i.test(clean))throw new Error('invalid');return new TextDecoder().decode(Uint8Array.from(clean.match(/../g)!.map((part)=>parseInt(part,16)))); }
    case 'text-to-hex': return [...new TextEncoder().encode(input)].map((byte)=>byte.toString(16).padStart(2,'0')).join(' ');
    case 'http-status-lookup': { const code=Math.trunc(num(values,'input')); const name=httpStatuses[code]; return name?`${code} ${name}\n${code<200?'Informational':code<300?'Success':code<400?'Redirection':code<500?'Client error':'Server error'}`:tr('Status code not found in the local reference.','Código no encontrado en la referencia local.'); }
    case 'mime-type-lookup': { const key=input.toLowerCase().trim().replace(/^.*\./,''); const direct=Object.entries(mimeTypes).find(([,mime])=>mime===input.toLowerCase().trim()); const mime=mimeTypes[key]; return direct?`.${direct[0]} — ${direct[1]}`:mime?`.${key} — ${mime}`:tr('MIME type not found in the local reference.','Tipo MIME no encontrado en la referencia local.'); }
    case 'port-number-lookup': { const port=Math.trunc(num(values,'input')); if(port<0||port>65535)throw new Error('invalid'); return ports[port]?`${port} — ${ports[port]}`:`${port} — ${tr('No common service in the local reference','Sin servicio común en la referencia local')}\n${port<1024?'Well-known port':port<49152?'Registered range':'Dynamic/private range'}`; }
    case 'user-agent-parser': { const os=/Windows NT/.test(input)?'Windows':/Android/.test(input)?'Android':/(iPhone|iPad)/.test(input)?'iOS':/Mac OS X/.test(input)?'macOS':/Linux/.test(input)?'Linux':'Unknown'; const browser=/Edg\//.test(input)?'Edge':/Firefox\//.test(input)?'Firefox':/Chrome\//.test(input)?'Chrome':/Safari\//.test(input)?'Safari':'Unknown'; const device=/(Mobile|Android|iPhone)/.test(input)?'Mobile':/iPad|Tablet/.test(input)?'Tablet':'Desktop'; return `${tr('Browser','Navegador')}: ${browser}\n${tr('Operating system','Sistema operativo')}: ${os}\n${tr('Device class','Tipo de dispositivo')}: ${device}\n${tr('Bot','Bot')}: ${/bot|crawler|spider/i.test(input)?tr('Yes','Sí'):tr('No','No')}`; }
    case 'gitignore-generator': { const common='.DS_Store\nThumbs.db\n.env\n.env.*\n!.env.example\n'; const templates:Record<string,string>={node:'node_modules/\ndist/\n.astro/\n.next/\ncoverage/\n*.log\n',python:'__pycache__/\n*.py[cod]\n.venv/\nvenv/\ndist/\n.pytest_cache/\n',rust:'target/\nCargo.lock\n',go:'bin/\n*.test\n*.out\nvendor/\n',mac:'.AppleDouble\n.LSOverride\nIcon\r\n'};return `${common}${templates[values.stack]??''}`; }
    case 'docker-run-builder': { if(!values.image?.trim())throw new Error('invalid'); const args=['docker run -d']; if(values.name)args.push(`--name ${shell(values.name)}`);if(values.hostPort&&values.containerPort)args.push(`-p ${num(values,'hostPort')}:${num(values,'containerPort')}`);args.push(shell(values.image));return args.join(' '); }
    case 'ssh-command-builder': { if(!values.host?.trim())throw new Error('invalid'); const args=['ssh'];if(values.port&&values.port!=='22')args.push(`-p ${num(values,'port')}`);if(values.key)args.push(`-i ${shell(values.key)}`);args.push(shell(`${values.user?`${values.user}@`:''}${values.host}`));return args.join(' '); }
    case 'regex-escape': return input.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
    case 'regex-flags-explainer': { const info:Record<string,string>={g:'g — global: find all matches',i:'i — ignore case',m:'m — multiline anchors',s:'s — dot matches newlines',u:'u — Unicode-aware',y:'y — sticky search',d:'d — match indices',v:'v — Unicode sets'}; const flags=uniqueLines([...input.trim()]);if(flags.some((flag)=>!info[flag]))throw new Error('invalid');return flags.map((flag)=>info[flag]).join('\n'); }
    case 'json-sorter': return JSON.stringify(sortObject(JSON.parse(input)),null,2);
    case 'json-flattener': return JSON.stringify(flatten(JSON.parse(input)),null,2);
    case 'json-unflattener': { const flat=JSON.parse(input);if(!flat||typeof flat!=='object'||Array.isArray(flat))throw new Error('invalid');const result:Record<string,unknown>={};Object.entries(flat).forEach(([path,value])=>{const keys=path.split('.');let cursor:Record<string,unknown>=result;keys.forEach((key,index)=>{if(index===keys.length-1)cursor[key]=value;else cursor=(cursor[key]??={}) as Record<string,unknown>})});return JSON.stringify(result,null,2); }
    case 'json-schema-generator': { const schema=schemaFor(JSON.parse(input));return JSON.stringify({$schema:'https://json-schema.org/draft/2020-12/schema',...schema},null,2); }
    case 'xml-escape': { if(values.direction==='decode'){const area=document.createElement('textarea');area.innerHTML=input;return area.value;}return input.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;'); }
    case 'sql-in-list-builder': { const items=input.split(/\r?\n|,/).map((item)=>item.trim()).filter(Boolean);if(!items.length)throw new Error('invalid');return `IN (${items.map((item)=>/^[-+]?\d+(?:\.\d+)?$/.test(item)?item:`'${item.replaceAll("'","''")}'`).join(', ')})`; }
    case 'environment-variable-parser': { const result:Record<string,string>={};input.split(/\r?\n/).forEach((line)=>{const clean=line.trim();if(!clean||clean.startsWith('#'))return;const index=clean.indexOf('=');if(index<1)throw new Error('invalid');let value=clean.slice(index+1).trim();if((value.startsWith('"')&&value.endsWith('"'))||(value.startsWith("'")&&value.endsWith("'")))value=value.slice(1,-1);result[clean.slice(0,index).trim()]=value});return JSON.stringify(result,null,2); }
    case 'ini-parser': { const result:Record<string,Record<string,string>>={root:{}};let section='root';input.split(/\r?\n/).forEach((line)=>{const clean=line.trim();if(!clean||clean.startsWith(';')||clean.startsWith('#'))return;const match=clean.match(/^\[([^\]]+)\]$/);if(match){section=match[1];result[section]??={};return;}const index=clean.indexOf('=');if(index<1)throw new Error('invalid');result[section][clean.slice(0,index).trim()]=clean.slice(index+1).trim()});if(!Object.keys(result.root).length)delete result.root;return JSON.stringify(result,null,2); }
    case 'semver-compare': { const a=parseSemver(values.a),b=parseSemver(values.b);let comparison=0;for(let i=0;i<3&&!comparison;i++)comparison=Math.sign(a.numbers[i]-b.numbers[i]);if(!comparison&&a.pre!==b.pre)comparison=!a.pre?1:!b.pre?-1:a.pre.localeCompare(b.pre,undefined,{numeric:true});return comparison===0?tr('The versions are equal.','Las versiones son iguales.'):comparison>0?`${values.a} > ${values.b}`:`${values.a} < ${values.b}`; }
    case 'semver-bump': { const parsed=parseSemver(input),[major,minor,patch]=parsed.numbers;return values.level==='major'?`${major+1}.0.0`:values.level==='minor'?`${major}.${minor+1}.0`:`${major}.${minor}.${patch+1}`; }
    case 'color-contrast-checker': { const l1=luminance(hexRgb(values.foreground)),l2=luminance(hexRgb(values.background)),ratio=(Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05);return `${tr('Contrast ratio','Relación de contraste')}: ${ratio.toFixed(2)}:1\nAA ${tr('normal text','texto normal')}: ${ratio>=4.5?'✓':'✗'}\nAA ${tr('large text','texto grande')}: ${ratio>=3?'✓':'✗'}\nAAA ${tr('normal text','texto normal')}: ${ratio>=7?'✓':'✗'}`; }
    case 'css-clamp-calculator': { const min=num(values,'min'),max=num(values,'max'),minV=num(values,'minViewport'),maxV=num(values,'maxViewport');if(maxV<=minV||max<min)throw new Error('invalid');const slope=(max-min)/(maxV-minV)*100,intercept=min-slope*minV/100;return `clamp(${f(min/16,4)}rem, ${f(intercept/16,4)}rem + ${f(slope,4)}vw, ${f(max/16,4)}rem)`; }
    case 'data-uri-generator': return `data:${values.mime};charset=utf-8,${encodeURIComponent(input)}`;
    case 'checksum-compare': { const clean=(value:string)=>value.trim().toLowerCase().replace(/\s/g,'');if(!clean(values.a)||!clean(values.b))throw new Error('invalid');return clean(values.a)===clean(values.b)?tr('Match — both checksums are identical.','Coinciden: ambos checksums son idénticos.'):tr('No match — the checksums are different.','No coinciden: los checksums son diferentes.'); }
    case 'random-data-generator': { const count=Math.min(100,Math.max(1,Math.trunc(num(values,'count'))));const rows=Array.from({length:count},(_,index)=>({id:index+1,code:`T-${randomInt(1_000_000).toString().padStart(6,'0')}`,active:Boolean(randomInt(2)),score:randomInt(101)}));return values.format==='csv'?`id,code,active,score\n${rows.map((row)=>Object.values(row).join(',')).join('\n')}`:JSON.stringify(rows,null,2); }
    case 'fake-user-generator': { const first=['Alex','Sam','Taylor','Jordan','Casey','Morgan','Avery','Riley'],last=['Rivera','Martin','Smith','García','Brown','Wilson','Lee','Santos'];const count=Math.min(50,Math.max(1,Math.trunc(num(values,'count'))));const rows=Array.from({length:count},(_,index)=>{const firstName=randomFrom(first),lastName=randomFrom(last);return {id:index+1,name:`${firstName} ${lastName}`,email:`${firstName}.${lastName}${randomInt(100)}@example.test`.toLowerCase(),role:randomFrom(['viewer','editor','admin'])}});return JSON.stringify(rows,null,2); }
    case 'api-response-mocker': { const count=Math.min(50,Math.max(1,Math.trunc(num(values,'count'))));const builders:Record<string,(id:number)=>object>={users:(id)=>({id,name:`User ${id}`,email:`user${id}@example.test`,active:id%3!==0}),products:(id)=>({id,name:`Product ${id}`,price:Number((9.95+id*3.5).toFixed(2)),stock:randomInt(30)}),posts:(id)=>({id,title:`Example post ${id}`,body:'Locally generated placeholder content.',published:id%2===0})};return JSON.stringify({data:Array.from({length:count},(_,index)=>builders[values.resource](index+1)),meta:{count}},null,2); }
    case 'graphql-query-minifier': return input.replace(/#[^\n\r]*/g,'').replace(/[\s,]+/g,' ').replace(/\s*([{}():!$=\[\]])\s*/g,'$1').trim();

    case 'tip-calculator': { const amount=num(values,'amount'),percent=num(values,'percent'),tip=amount*percent/100;return `${tr('Tip','Propina')}: ${f(tip,2)}\n${tr('Total','Total')}: ${f(amount+tip,2)}`; }
    case 'split-bill-calculator': { const amount=num(values,'amount'),tipRate=num(values,'tip'),people=num(values,'people');if(amount<0||people<=0)throw new Error('invalid');const tip=amount*tipRate/100,total=amount+tip;return `${tr('Subtotal','Subtotal')}: ${f(amount,2)}\n${tr('Tip','Propina')}: ${f(tip,2)}\n${tr('Total','Total')}: ${f(total,2)}\n${tr('Per person','Por persona')}: ${f(total/people,2)}`; }
    case 'loan-payment-calculator': { const principal=num(values,'principal'),rate=num(values,'rate')/1200,months=num(values,'years')*12;if(principal<0||months<=0)throw new Error('invalid');const payment=rate===0?principal/months:principal*rate*(1+rate)**months/((1+rate)**months-1);return `${tr('Monthly payment','Cuota mensual')}: ${f(payment,2)}\n${tr('Total paid','Total pagado')}: ${f(payment*months,2)}\n${tr('Total interest','Intereses totales')}: ${f(payment*months-principal,2)}`; }
    case 'compound-interest-calculator': { const principal=num(values,'principal'),rate=num(values,'rate')/100,years=num(values,'years'),frequency=num(values,'frequency');if(principal<0||years<0||frequency<=0)throw new Error('invalid');const total=principal*(1+rate/frequency)**(frequency*years);return `${tr('Final balance','Saldo final')}: ${f(total,2)}\n${tr('Interest earned','Intereses generados')}: ${f(total-principal,2)}`; }
    case 'simple-interest-calculator': { const principal=num(values,'principal'),interest=principal*num(values,'rate')/100*num(values,'years');return `${tr('Interest','Interés')}: ${f(interest,2)}\n${tr('Final balance','Saldo final')}: ${f(principal+interest,2)}`; }
    case 'savings-goal-calculator': { const remaining=num(values,'goal')-num(values,'current'),months=num(values,'months');if(months<=0)throw new Error('invalid');return `${tr('Still needed','Falta por ahorrar')}: ${f(Math.max(0,remaining),2)}\n${tr('Monthly contribution','Aportación mensual')}: ${f(Math.max(0,remaining)/months,2)}`; }
    case 'roi-calculator': { const cost=num(values,'cost'),returned=num(values,'return');if(cost===0)throw new Error('invalid');return `${tr('Net result','Resultado neto')}: ${f(returned-cost,2)}\nROI: ${f((returned-cost)/Math.abs(cost)*100,2)}%`; }
    case 'profit-margin-calculator': { const cost=num(values,'cost'),price=num(values,'price');if(price===0)throw new Error('invalid');return `${tr('Profit','Beneficio')}: ${f(price-cost,2)}\n${tr('Margin','Margen')}: ${f((price-cost)/price*100,2)}%`; }
    case 'markup-calculator': { const cost=num(values,'cost'),price=num(values,'price');if(cost===0)throw new Error('invalid');return `${tr('Profit','Beneficio')}: ${f(price-cost,2)}\nMarkup: ${f((price-cost)/cost*100,2)}%`; }
    case 'break-even-calculator': { const fixed=num(values,'fixed'),margin=num(values,'price')-num(values,'variable');if(margin<=0)throw new Error('invalid');const units=Math.ceil(fixed/margin);return `${tr('Break-even units','Unidades para equilibrio')}: ${units}\n${tr('Contribution per unit','Contribución por unidad')}: ${f(margin,2)}\n${tr('Break-even revenue','Ingresos de equilibrio')}: ${f(units*num(values,'price'),2)}`; }
    case 'salary-hourly-converter': { const hours=num(values,'hours')*num(values,'weeks');if(hours<=0)throw new Error('invalid');return `${tr('Hourly rate','Tarifa por hora')}: ${f(num(values,'salary')/hours,2)}\n${tr('Monthly equivalent','Equivalente mensual')}: ${f(num(values,'salary')/12,2)}`; }
    case 'freelance-rate-calculator': { const hours=num(values,'hours');if(hours<=0)throw new Error('invalid');return `${tr('Minimum hourly rate','Tarifa horaria mínima')}: ${f((num(values,'target')+num(values,'costs'))/hours,2)}\n${tr('Revenue target','Objetivo de facturación')}: ${f(num(values,'target')+num(values,'costs'),2)}`; }
    case 'fuel-cost-calculator': { const litres=num(values,'distance')*num(values,'consumption')/100;return `${tr('Fuel needed','Combustible necesario')}: ${f(litres,2)} L\n${tr('Estimated cost','Coste estimado')}: ${f(litres*num(values,'price'),2)}`; }
    case 'electricity-cost-calculator': { const kwh=num(values,'watts')/1000*num(values,'hours');return `${tr('Energy used','Energía consumida')}: ${f(kwh,3)} kWh\n${tr('Estimated cost','Coste estimado')}: ${f(kwh*num(values,'price'),2)}`; }
    case 'pace-calculator': { const distance=num(values,'distance'),seconds=num(values,'hours')*3600+num(values,'minutes')*60+num(values,'seconds');if(distance<=0||seconds<=0)throw new Error('invalid');const pace=seconds/distance,paceMin=Math.floor(pace/60),paceSec=Math.round(pace%60),speed=distance/(seconds/3600);return `${tr('Pace','Ritmo')}: ${paceMin}:${String(paceSec).padStart(2,'0')} min/km\n${tr('Average speed','Velocidad media')}: ${f(speed,2)} km/h`; }
    case 'bmi-calculator': { const height=num(values,'height')/100,bmi=num(values,'weight')/height**2;if(height<=0)throw new Error('invalid');const category=bmi<18.5?tr('Underweight','Peso bajo'):bmi<25?tr('Healthy range','Rango saludable'):bmi<30?tr('Overweight','Sobrepeso'):tr('Obesity range','Rango de obesidad');return `BMI / IMC: ${f(bmi,1)}\n${tr('Reference category','Categoría orientativa')}: ${category}`; }
    case 'calorie-needs-calculator': { const base=10*num(values,'weight')+6.25*num(values,'height')-5*num(values,'age')+(values.sex==='male'?5:-161),total=base*num(values,'activity');return `${tr('Basal estimate','Estimación basal')}: ${f(base,0)} kcal/day\n${tr('Maintenance estimate','Estimación de mantenimiento')}: ${f(total,0)} kcal/day\n${tr('Informational estimate, not medical advice.','Estimación orientativa, no es consejo médico.')}`; }
    case 'body-fat-estimator': { const estimate=1.2*num(values,'bmi')+.23*num(values,'age')-10.8*(values.sex==='male'?1:0)-5.4;return `${tr('Estimated body fat','Grasa corporal estimada')}: ${f(estimate,1)}%\n${tr('Screening estimate only, not a diagnosis.','Solo estimación orientativa, no es un diagnóstico.')}`; }
    case 'rule-of-three-calculator': { const a=num(values,'a');if(a===0)throw new Error('invalid');const result=num(values,'b')*num(values,'c')/a;return `A : B = C : X\nX = (B × C) ÷ A = ${f(result)}`; }
    case 'fraction-simplifier': { let numerator=Math.trunc(num(values,'numerator')),denominator=Math.trunc(num(values,'denominator'));if(!denominator)throw new Error('invalid');const divisor=gcd(numerator,denominator);numerator/=divisor;denominator/=divisor;if(denominator<0){numerator=-numerator;denominator=-denominator;}return `${numerator}/${denominator}\n${tr('Decimal','Decimal')}: ${f(numerator/denominator)}`; }
    case 'fraction-to-decimal': { const denominator=num(values,'denominator');if(!denominator)throw new Error('invalid');return `${num(values,'numerator')} ÷ ${denominator} = ${f(num(values,'numerator')/denominator,12)}`; }
    case 'decimal-to-fraction': { const value=num(values,'input');const raw=input.toLowerCase();if(raw.includes('e')){const precision=1_000_000,top=Math.round(value*precision),divisor=gcd(top,precision);return `${top/divisor}/${precision/divisor}`;}const decimals=(raw.split('.')[1]??'').length,denominator=10**Math.min(decimals,12),numerator=Math.round(value*denominator),divisor=gcd(numerator,denominator);return `${numerator/divisor}/${denominator/divisor}`; }
    case 'scientific-notation-converter': { const value=num(values,'input');if(value===0)return '0 = 0 × 10⁰';const exponent=Math.floor(Math.log10(Math.abs(value))),coefficient=value/10**exponent;return `${value.toLocaleString(locale,{maximumFractionDigits:12})}\n${f(coefficient,12)} × 10^${exponent}\n${value.toExponential(10).replace(/\.0+(?=e)|0+(?=e)/,'')}`; }
    case 'average-calculator': { const items=parseNumbers(input);if(!items.length)throw new Error('invalid');return `${tr('Count','Cantidad')}: ${items.length}\n${tr('Sum','Suma')}: ${f(items.reduce((a,b)=>a+b,0))}\n${tr('Average','Media')}: ${f(items.reduce((a,b)=>a+b,0)/items.length)}`; }
    case 'median-calculator': { const items=parseNumbers(input).sort((a,b)=>a-b);if(!items.length)throw new Error('invalid');const middle=Math.floor(items.length/2),median=items.length%2?items[middle]:(items[middle-1]+items[middle])/2;return `${tr('Sorted values','Valores ordenados')}: ${items.join(', ')}\n${tr('Median','Mediana')}: ${f(median)}`; }

    case 'age-calculator': { const birth=requireDate(values.birth),target=values.target?requireDate(values.target):new Date();if(target<birth)throw new Error('invalid');let years=target.getFullYear()-birth.getFullYear();let months=target.getMonth()-birth.getMonth();let days=target.getDate()-birth.getDate();if(days<0){months--;days+=new Date(target.getFullYear(),target.getMonth(),0).getDate();}if(months<0){years--;months+=12;}const totalDays=Math.floor((Date.UTC(target.getFullYear(),target.getMonth(),target.getDate())-Date.UTC(birth.getFullYear(),birth.getMonth(),birth.getDate()))/86400000);return `${years} ${tr('years','años')}, ${months} ${tr('months','meses')}, ${days} ${tr('days','días')}\n${tr('Total days','Días totales')}: ${totalDays}`; }
    case 'date-difference': { const start=requireDate(values.start),end=requireDate(values.end),days=Math.round((end.getTime()-start.getTime())/86400000);return `${tr('Difference','Diferencia')}: ${Math.abs(days)} ${tr('days','días')}\n${f(Math.abs(days)/7,2)} ${tr('weeks','semanas')}\n${days<0?tr('The end date is before the start date.','La fecha final es anterior a la inicial.'):''}`.trim(); }
    case 'business-days-calculator': { const start=requireDate(values.start),end=requireDate(values.end);if(end<start)throw new Error('invalid');let count=0,cursor=new Date(start);while(cursor<=end){const day=cursor.getDay();if(day!==0&&day!==6)count++;cursor.setDate(cursor.getDate()+1);}return `${count} ${tr('weekdays (Monday–Friday)','días laborables (lunes a viernes)')}\n${tr('Public holidays are not excluded.','No se descuentan los festivos.')}`; }
    case 'date-add-subtract': { const result=requireDate(values.start);result.setDate(result.getDate()+Math.trunc(num(values,'days')));return `${dateOnly(result)}\n${result.toLocaleDateString(locale,{weekday:'long',year:'numeric',month:'long',day:'numeric'})}`; }
    case 'week-number-calculator': { const date=requireDate(input),utc=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));utc.setUTCDate(utc.getUTCDate()+4-(utc.getUTCDay()||7));const yearStart=new Date(Date.UTC(utc.getUTCFullYear(),0,1)),week=Math.ceil((((utc.getTime()-yearStart.getTime())/86400000)+1)/7);return `${tr('ISO week','Semana ISO')}: ${week}\n${tr('ISO week year','Año de semana ISO')}: ${utc.getUTCFullYear()}`; }
    case 'day-of-year-calculator': { const date=requireDate(input),start=Date.UTC(date.getFullYear(),0,0),current=Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()),day=Math.floor((current-start)/86400000);return `${tr('Day of year','Día del año')}: ${day}\n${tr('Days remaining','Días restantes')}: ${(new Date(date.getFullYear(),1,29).getMonth()===1?366:365)-day}`; }
    case 'leap-year-checker': { const year=Math.trunc(num(values,'input')),yes=year%4===0&&(year%100!==0||year%400===0);return yes?`${year} ${tr('is a leap year (366 days).','es bisiesto (366 días).')}`:`${year} ${tr('is not a leap year (365 days).','no es bisiesto (365 días).')}`; }
    case 'timezone-offset-converter': { const source=requireDate(input),difference=(num(values,'to')-num(values,'from'))*3600000,result=new Date(source.getTime()+difference);return `${result.getFullYear()}-${String(result.getMonth()+1).padStart(2,'0')}-${String(result.getDate()).padStart(2,'0')} ${String(result.getHours()).padStart(2,'0')}:${String(result.getMinutes()).padStart(2,'0')} (UTC${num(values,'to')>=0?'+':''}${values.to})`; }
    case 'countdown-calculator': { const target=requireDate(input),difference=target.getTime()-Date.now(),past=difference<0,total=Math.abs(difference),days=Math.floor(total/86400000),hours=Math.floor(total%86400000/3600000),minutes=Math.floor(total%3600000/60000);return `${past?tr('Elapsed','Transcurrido'):tr('Remaining','Restante')}: ${days} ${tr('days','días')}, ${hours} ${tr('hours','horas')}, ${minutes} ${tr('minutes','minutos')}`; }
    case 'hours-minutes-calculator': { const a=num(values,'hoursA')*60+num(values,'minutesA'),b=num(values,'hoursB')*60+num(values,'minutesB'),total=values.operation==='subtract'?a-b:a+b,sign=total<0?'-':'',absolute=Math.abs(total);return `${sign}${Math.floor(absolute/60)}:${String(Math.round(absolute%60)).padStart(2,'0')}\n${tr('Total minutes','Minutos totales')}: ${f(total)}`; }
    case 'cooking-unit-converter': { const factors:Record<string,number>={ml:1,l:1000,tsp:4.92892,tbsp:14.7868,cup:236.588,floz:29.5735},result=num(values,'input')*factors[values.from]/factors[values.to];return `${f(num(values,'input'))} ${values.from} = ${f(result)} ${values.to}`; }
    case 'angle-converter': { const factors:Record<string,number>={deg:Math.PI/180,rad:1,grad:Math.PI/200,turn:Math.PI*2},result=num(values,'input')*factors[values.from]/factors[values.to];return `${f(num(values,'input'))} ${values.from} = ${f(result,10)} ${values.to}`; }
    case 'speed-converter': { const factors:Record<string,number>={kmh:1,ms:3.6,mph:1.609344,knot:1.852},result=num(values,'input')*factors[values.from]/factors[values.to];return `${f(num(values,'input'))} ${values.from} = ${f(result)} ${values.to}`; }
    case 'pressure-converter': { const factors:Record<string,number>={pa:1,kpa:1000,bar:100000,psi:6894.757293,atm:101325},result=num(values,'input')*factors[values.from]/factors[values.to];return `${f(num(values,'input'))} ${values.from} = ${f(result,8)} ${values.to}`; }
    case 'energy-converter': { const factors:Record<string,number>={j:1,kj:1000,cal:4.184,kcal:4184,wh:3600,kwh:3600000},result=num(values,'input')*factors[values.from]/factors[values.to];return `${f(num(values,'input'))} ${values.from} = ${f(result,8)} ${values.to}`; }
    default: throw new Error(`Unknown operation: ${operation}`);
  }
}
